Repository Bayer-Group/ol-kit, pull requests merged in 2020-06, with the labels that each got.

#105 [FEATURE] Google places search
  .eslintrc.json
  package-lock.json
  package.json
  src/GooglePlacesSearch/GooglePlacesSearch.js
  src/GooglePlacesSearch/index.js
  src/__snapshots__/index.test.js.snap
  src/index.js
Labels: enhancement, team reviewed :eyes:

#109 add CNAME file back for docs site
  docs/CNAME
Labels: urgent :warning:

#117 add support for clustered features clicks
  package-lock.json
  package.json
  src/Popup/Popup.js
  src/Popup/utils.js
  src/Popup/utils.test.js
Labels: bug :bug:, enhancement, ready to ship :rocket:, support :rescue_worker_helmet:, team reviewed :eyes:

#120 add clickPixel & clickCoordinate to onMapClick callback
  package-lock.json
  package.json
  src/Popup/Popup.js
  src/Popup/Popup.test.js
  src/index.js
Labels: enhancement, ready to ship :rocket:, team reviewed :eyes:

#124 add safeSelectedIdx check to prevent popup bug
  src/Popup/PopupInsert/PopupDefaultInsert.js
Labels: bug :bug:, external contribution :raised_hands:, ready to ship :rocket:, team reviewed :eyes:

#126 Demo App
  .github/workflows/deploy-to-s3.yml
  .gitignore
  .npmignore
  app/App.js
  app/favicon.ico
  app/index.html
  app/index.js
  app/webpack.config.js
  docs/LayerPanel_LayerPanelActionExport_index.js.html
  docs/LayerPanel_LayerPanelActionExport_utils.js.html
  docs/PopupActionGroup.html
  docs/PopupActionItem.html
  docs/PopupDataList.html
  docs/PopupDefaultPage.html
  docs/PopupPageLayout.html
  docs/PopupPageLayoutChild.html
  docs/PopupTabs.html
  docs/tutorial-Getting Started.html
  package-lock.json
  package.json
  src-docs/tutorials/Getting Started.md
  src/LayerPanel/LayerPanelActionExport/index.js
  src/LayerPanel/LayerPanelActionExport/utils.js
  src/Map/styled.js
Labels: ready to ship :rocket:, team reviewed :eyes:
