Repository Bayer-Group/ol-kit, pull requests merged in 2020-04, with the labels that each got.

#26 Adding back missing static folder
  .gitignore
  docs/static/bayer-logo.png
  docs/static/ol-kit-logo.png
  docs/static/readme-bayer-logo.png
  docs/static/readme-ol-kit-logo.png
Labels: documentation, ready to ship :rocket:

#29 Fixes README images
  README.md
Labels: documentation

#27 Added a safety check by using window.StickySidebar
  config/jsdoc/template/scripts/app.js
  docs/scripts/app.js
Labels: documentation

#36 Fixed mobile meta tag for docs
  config/jsdoc/template/tmpl/layout.tmpl
  docs/BasemapManager.html
  docs/Basemaps_BasemapManager.js.html
  docs/Basemaps_BingMaps.js.html
  docs/Basemaps_BlankWhite.js.html
  docs/Basemaps_OpenStreetMap.js.html
  docs/Basemaps_StamenTerrain.js.html
  docs/Basemaps_StamenTonerDark.js.html
  docs/Basemaps_StamenTonerLite.js.html
  docs/BingMaps.html
  docs/BlankWhite.html
  docs/Compass.html
  docs/Controls.html
  docs/Controls_Compass.js.html
  docs/Controls_Controls.js.html
  docs/Controls_ZoomControls.js.html
  docs/Map.html
  docs/Map_Map.js.html
  docs/Map_utils.js.html
  docs/OpenStreetMap.html
  docs/StamenTerrain.html
  docs/StamenTonerDark.html
  docs/StamenTonerLite.html
  docs/ZoomControls.html
  docs/docs.html
  docs/global.html
  docs/index.html
  docs/tutorial-Getting Started.html
  docs/tutorial-connectToMap.html
  docs/tutorial-i18n Support.html
  src-docs/overrides/index.html
Labels: documentation

#30 VectorLayer class
  package-lock.json
  package.json
  src/Basemaps/BasemapManager.test.js
  src/Basemaps/__snapshots__/BasemapManager.test.js.snap
  src/__snapshots__/index.test.js.snap
  src/classes/VectorLayer.js
  src/classes/VectorLayer.test.js
  src/index.js
Labels: ready to ship :rocket:, team reviewed :eyes:

#33 Doc updates
  MAINTAINERS.md
  docs/index.html
  docs/tutorial-Getting Started.html
  package-lock.json
  package.json
  src-docs/overrides/index.html
  src-docs/tutorials/Getting Started.md
Labels: documentation

#40 Add React to imports for example
  docs/index.html
Labels: bug, documentation

#45 fix bad file path
  package-lock.json
  package.json
  src/Popup/PopupInsert/PopupPageLayoutChild/index.js
Labels: bug, ready to ship :rocket:

#47 fix loading type of string console warning
  package-lock.json
  src/Popup/PopupInsert/PopupDefaultPage/index.js
  src/Popup/PopupInsert/PopupHeader/styled.js
Labels: ready to ship :rocket:

#46 Added a .gitattributes file to help GH linguist understand the project
  .gitattributes
Labels: documentation

#51 Feature: Added GH Action to Lint and Test PRs
  .github/workflows/integrate.yml
Labels: ready to ship :rocket:, team reviewed :eyes:

#49 Fix: README boiler plate
  .gitattributes
  README.md
Labels: question, ready to ship :rocket:, team reviewed :eyes:

#55 build the docs with latest popup changes
  docs/PopupActionGroup.html
  docs/PopupActionItem.html
  docs/PopupDataList.html
  docs/PopupDefaultPage.html
  docs/PopupPageLayout.html
  docs/PopupPageLayoutChild.html
  docs/PopupTabs.html
  docs/tutorial-Popup_.html
  src-docs/tutorials/Popup.md
Labels: documentation
