Repository Bayer-Group/ol-kit, pull requests merged in 2020-10, with the labels that each got.

#205 add internal catch for errors in onMapInit block
  package-lock.json
  package.json
  src/Draw/__snapshots__/DrawContainer.test.js.snap
  src/Map/Map.js
Labels: external contribution :raised_hands:, ready to review :crossed_fingers:

#219 use devDependencies in ol-kit to run app
  app/package-lock.json
  package-lock.json
  package.json
Labels: support :rescue_worker_helmet:, urgent :warning:

#222 Resolved map not displaying without fullScreen prop error+ installed cross-env for env vars to work on windows OS
  package-lock.json
  package.json
Labels: external contribution :raised_hands:, hacktoberfest-accepted, ready to ship :rocket:, team reviewed :eyes:

#226 Remove Diltz's Crib from demo
  app/demos/world/App.js
  cli/generator/prompt.js
  cli/index.js
Labels: ready to review :crossed_fingers:

#229 fix bugs with flyout menu in popup
  package-lock.json
  package.json
  src/Popup/PopupInsert/PopupActionGroup/index.js
  src/Popup/PopupInsert/PopupActionGroup/styled.js
Labels: bug :bug:, support :rescue_worker_helmet:

#231 Fixed out-of-date links to pages in OpenLayers website.
  src/Map/example.md
  src/Map/utils.js
  src/Popup/utils.js
  src/Popup/utils.test.js
  src/classes/VectorLayer.js
Labels: documentation, external contribution :raised_hands:, hacktoberfest-accepted, ready to ship :rocket:

#236 always render map and log errors from onMapInit
  package-lock.json
  package.json
  src/Draw/__snapshots__/DrawContainer.test.js.snap
  src/Map/Map.js
Labels: support :rescue_worker_helmet:, urgent :warning:

#161 New layerpanel design
  app/Router.js
  app/demos/world/App.js
  app/tests/LayerPanel.js
  package-lock.json
  src/LayerPanel/LayerPanel.js
  src/LayerPanel/LayerPanelBase/index.js
  src/LayerPanel/LayerPanelBase/styled.js
  src/LayerPanel/LayerPanelLayersPage/index.js
  src/LayerPanel/LayerPanelPage/example.md
  src/LayerPanel/LayerPanelPage/index.js
  src/LayerPanel/example.md
Labels: ready to ship :rocket:, team reviewed :eyes:
