Repository Bayer-Group/ol-kit, pull requests merged in 2020-07, with the labels that each got.

#136 add no-console errors to linter
  .eslintrc.json
  package-lock.json
  package.json
  src/DataLayers/utils.test.js
  src/Popup/Popup.test.js
Labels: ready to ship :rocket:, team reviewed :eyes:

#137 Integration Tests
  app/App.js
  app/integration.sh
  app/tests/LayerPanel.js
  app/tests/pupp-utils.js
  package-lock.json
  package.json
  src/DataLayers/utils.js
  src/LayerPanel/LayerPanel.test.js
  src/LayerPanel/LayerPanelActionExtent/index.js
  src/LayerPanel/LayerPanelActionOpacity/index.js
  src/LayerPanel/LayerPanelActionRemove/index.js
  src/LayerPanel/LayerPanelActions/index.js
  src/LayerPanel/LayerPanelBase/index.js
  src/LayerPanel/LayerPanelCheckbox/index.js
  src/LayerPanel/LayerPanelLayersPage/index.js
  src/LayerPanel/LayerPanelMenu/index.js
  src/LayerPanel/LayerPanelPage/index.js
  src/LayerPanel/_LayerPanelExpandableList/index.js
Labels: ready to ship :rocket:, team reviewed :eyes:

#139 Replace react-smooth-dnd
  package-lock.json
  package.json
  src/LayerPanel/LayerPanelList/index.js
Labels: ready to review :crossed_fingers:, team reviewed :eyes:

#144 remove material-ui/lab
  package-lock.json
  package.json
  src/GooglePlacesSearch/GooglePlacesSearch.js
Labels: ready to review :crossed_fingers:
