Repository Bayer-Group/ol-kit, pull requests merged in 2020-05, with the labels that each got.

#70 document material ui peerDependencies
  README.md
  docs/PopupActionGroup.html
  docs/PopupActionItem.html
  docs/PopupDataList.html
  docs/PopupDefaultPage.html
  docs/PopupPageLayout.html
  docs/PopupPageLayoutChild.html
  docs/PopupTabs.html
  docs/index.html
  docs/tutorial-Getting Started.html
  src-docs/overrides/index.html
  src-docs/tutorials/Getting Started.md
Labels: documentation, ready to ship :rocket:, team reviewed :eyes:, urgent :warning:

#71 export all the missing Popup building blocks
  docs/PopupActionGroup.html
  docs/PopupActionItem.html
  docs/PopupDataList.html
  docs/PopupDefaultInsert.html
  docs/PopupDefaultPage.html
  docs/PopupPageLayout.html
  docs/PopupPageLayoutChild.html
  docs/PopupTabs.html
  docs/Popup_Popup.js.html
  docs/Popup_PopupInsert_PopupDefaultInsert.js.html
  docs/Popup_PopupInsert_PopupDefaultPage_index.js.html
  docs/Popup_utils.js.html
  docs/global.html
  docs/tutorial-i18n Support.html
  package-lock.json
  package.json
  src-docs/tutorials/i18n Support.md
  src/Popup/Popup.js
  src/Popup/PopupInsert/PopupDefaultInsert.js
  src/Popup/PopupInsert/PopupDefaultPage/index.js
  src/Popup/PopupInsert/index.js
  src/Popup/index.js
  src/Popup/styled.js
  src/Popup/utils.js
  src/__snapshots__/index.test.js.snap
Labels: ready to ship :rocket:, team reviewed :eyes:

#100 patch to get valid layers for layer styler
  docs/LayerStyler_LayerStyler.js.html
  docs/PopupActionGroup.html
  docs/PopupActionItem.html
  docs/PopupDataList.html
  docs/PopupDefaultPage.html
  docs/PopupPageLayout.html
  docs/PopupPageLayoutChild.html
  docs/PopupTabs.html
  package-lock.json
  package.json
  src/LayerStyler/LayerStyler.js
  src/locales/en.js
Labels: bug :bug:, ready to ship :rocket:
