Repository Bayer-Group/ol-kit, pull requests merged in 2021-08, with the labels that each got.

#262 Removed runjs in favor of vanillajs scripts
  package-lock.json
  package.json
  runfile.js
  scripts/preventPublish.js
  scripts/ship.js
Labels: question :grey_question:, team reviewed :eyes:

#326 Audit vulnerabilities
  app/webpack.config.js
  package-lock.json
  package.json
  src/Draw/__snapshots__/DrawContainer.test.js.snap
Labels: team reviewed :eyes:, ready to ship :rocket:

#328 VM2091 - Zoom to Feature
  src/Map/utils.js
  src/Popup/PopupActions/PopupActionZoomToExtent/PopupActionZoomToExtent.js
  src/Popup/PopupActions/PopupActionZoomToExtent/index.js
  src/Popup/PopupInsert/PopupDefaultInsert.js
  src/__snapshots__/index.test.js.snap
  src/locales/en.js
Labels: ready to review :crossed_fingers:
