Repository Bayer-Group/ol-kit, pull requests merged in 2021-01, with the labels that each got.

#259 Context Menu Children fix
  src/ContextMenu/ContextMenu.js
Labels: bug :bug:, external contribution :raised_hands:

#256 Popup action item onClick should provide ol feature as prop
  src/Popup/PopupInsert/PopupActionGroup/index.js
  src/Popup/PopupInsert/PopupActionItem/index.js
Labels: enhancement, external contribution :raised_hands:

#246 Vector tile support
  app/Router.js
  app/demos/vector-tiles/App.js
  package-lock.json
  package.json
  src/Draw/__snapshots__/DrawContainer.test.js.snap
  src/LayerStyler/LayerStyler.js
  src/Popup/utils.js
  src/__snapshots__/index.test.js.snap
  src/classes/VectorTileLayer.js
  src/classes/index.js
Labels: ready to ship :rocket:, team reviewed :eyes:

#266 make the layer panel scrollable
  src/LayerPanel/LayerPanelBase/styled.js
Labels: bug :bug:, external contribution :raised_hands:

#263 Updates from supportv0 that need to be moved to 1.0
  package-lock.json
  package.json
  src/Draw/__snapshots__/DrawContainer.test.js.snap
  src/LayerPanel/LayerPanelActionRemove/index.js
  src/LayerPanel/LayerPanelLayersPage/index.js
Labels: pending changes, ready to ship :rocket:, team reviewed :eyes:
