Repository Bayer-Group/ol-kit, pull requests merged in 2021-03, with the labels that each got.

#289 Update Popup Design
  package-lock.json
  src/Popup/PopupBase.js
  src/Popup/PopupInsert/PopupDataList/styled.js
  src/Popup/PopupInsert/PopupDefaultInsert.js
  src/Popup/PopupInsert/PopupDefaultPage/index.js
  src/Popup/PopupInsert/PopupHeader/styled.js
  src/Popup/styled.js
Labels: enhancement, team reviewed :eyes:

#288 Default popup actions
  package-lock.json
  package.json
  src/Popup/PopupActions/PopupActionCopyWkt/PopupActionCopyWkt.js
  src/Popup/PopupActions/PopupActionDuplicate/PopupActionDuplicate.js
  src/Popup/PopupActions/PopupActionDuplicate/index.js
  src/Popup/PopupActions/PopupActionRemove/PopupActionRemove.js
  src/Popup/PopupActions/PopupActionRemove/index.js
  src/Popup/PopupInsert/PopupDefaultInsert.js
  src/Popup/PopupInsert/PopupDefaultPage/index.js
  src/Snackbar/Snackbar.js
  src/Snackbar/index.js
  src/__snapshots__/index.test.js.snap
  src/index.js
  src/locales/en.js
Labels: ready to ship :rocket:, team reviewed :eyes:

#287 Image Exif Viewer
  app/Router.js
  app/Welcome.js
  app/demos/image-exif/App.js
  app/demos/image-exif/index.js
  app/demos/image-exif/styled.js
  package-lock.json
  package.json
  src/ImageExif/ImageExif.js
  src/ImageExif/arrow.png
  src/ImageExif/index.js
  src/ImageExif/styled.js
  src/TabbedPanel/styled.js
  src/locales/en.js
Labels: enhancement, ready to ship :rocket:, team reviewed :eyes:
